INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Lawrence", "Tan", "lawrence.tan@everbright.edu.sg", "tantan", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Jennifer", "Wong", "jennifer.wong@everbright.edu.sg", "jwong", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Clare", "Lim", "clare.lim@everbright.edu.sg", "clim", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Ann", "Maria", "ann.maria@everbright.edu.sg", "amaria", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Shubha", "Manohar", "shubha.manohar@everbright.edu.sg", "smanohar", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Sundar", "Lal", "sundar.lal@everbright.edu.sg", "slal", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Fatima", "Ismail", "fatima.ismail@everbright.edu.sg", "fismail", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Rahman", "Mohammed", "rahman.mohammed@everbright.edu.sg", "rmohammed", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Sean", "Jackson", "sean.jackson@everbright.edu.sg", "sjackson", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "MengLong", "Tan", "menglong.tan@everbright.edu.sg", "mltan", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "SiewWai", "Ng", "siewwai.ng@everbright.edu.sg", "swainng", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Jane", "Chow", "jane.chow@everbright.edu.sg", "jchow", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Sheela", "Narayan", "sheela.narayan@everbright.edu.sg", "snarayan", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Park", "Liew", "park.liew@everbright.edu.sg", "pliew", "password");
INSERT INTO lecturer(id, first_name, last_name, email, username, password) VALUES(uuid(), "Ranbir", "Das", "ranbir.das@everbright.edu.sg", "rdas", "password");

INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "luke", "Sim", "luke.sim@gmail.com", "lsim", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Hank", "Chua", "hank.chua@everbright.edu.sg", "hchua", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Nimmy", "Fernandus", "nimmy.fernadus@everbright.edu.sg", "nfernadus", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Fedrick", "Sim", "fedrick.sim@gmail.com", "fsim", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Patricia", "lim", "patricia.lim@everbright.edu.sg", "plim", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Sreejith", "Divakaran", "sreejith.divakaran@gmail.com", "sdivakaran", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Shalini", "Mathew", "shalini.mathew@gmail.com", "smathw", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Siewwai", "Long", "siewwai.long@everbright.edu.sg", "slong", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Zhao", "Bin", "zhao.bin@everbright.edu.sg", "sbin", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "ZhiMin", "Ling", "zhimin.ling@gmail.com", "sling", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Arkar", "Aye", "arkar.aye@everbright.edu.sg", "aaye", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Wei", "Xiang", "wei.xiang@everbright.edu.sg", "wxiang", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "George", "Mathews", "george.mathews@gmail.com", "gmathews", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Pete", "Sim", "pete.sim@gmail.com", "psim", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Mark", "Chua", "mark.chua@everbright.edu.sg", "mchua", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Trisha", "Lopez", "trisha.lopez@everbright.edu.sg", "tlopez", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Freddy", "Tan", "freddy.tan@gmail.com", "ftan", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Patricia", "Liew", "patricia.liew@everbright.edu.sg", "ptliew", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Saran", "Kishan", "saran.kishan@gmail.com", "skishan", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Srilaxmi", "Thekkil", "srilaxmi.thekkil@gmail.com", "sthekkil", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Jane", "Long", "Jane.long@everbright.edu.sg", "jlong", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Qi", "Bin", "qi.bin@everbright.edu.sg", "qbin", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "ZhiMin", "Ming", "zhimin.ming@gmail.com", "sming", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Nyang", "Aye", "nyang.aye@everbright.edu.sg", "naye", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "Wei", "Dong", "wei.dong@everbright.edu.sg", "wdong", "password");
INSERT INTO student(id, first_name, last_name, email, username, password) VALUES(uuid(), "James", "Cannon", "james.cannon@gmail.com", "gcannon", "password");

INSERT INTO admin(id, first_name, last_name, email, username, password) VALUES(uuid(), "Meena", "Subhash", "meena.subhash@gmail.com", "admin1", "password");
INSERT INTO admin(id, first_name, last_name, email, username, password) VALUES(uuid(), "Jake", "Lim", "jake.lim@everbright.edu.sg", "admin2", "password");

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Computational Mathematics", "Computational applied mathematics consists roughly of using mathematics for allowing and improving computer computation in applied mathematics. Computational mathematics may also refer to the use of computers for mathematics itself. This includes the use of computers for mathematical computations (computer algebra), the study of what can (and cannot) be computerized in mathematics (effective methods), which computations may be done with present technology (complexity theory), and which proofs can be done on computers", 15, 15, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Programming Concepts Using C#", "C# is a general-purpose, multi-paradigm programming language. C# encompasses static typing, strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Data Structures and Algorithms", "In computer science, a data structure is a data organization, management, and storage format that enables efficient access and modification.More precisely, a data structure is a collection of data values, the relationships among them, and the functions or operations that can be applied to the data. In mathematics and computer science, an algorithm is a finite sequence of rigorous instructions, typically used to solve a class of specific problems or to perform a computation.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Computer Security", "Computer security, cybersecurity (cyber security), or information technology security (IT security) is the protection of computer systems and networks from information disclosure, theft of, or damage to their hardware, software, or electronic data, as well as from the disruption or misdirection of the services they provide. The field has become significant due to the expanded reliance on computer systems, the Internet, and wireless network", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Digital image Processing", "Digital image processing is the use of a digital computer to process digital images through an algorithm. As a subcategory or field of digital signal processing, digital image processing has many advantages over analog image processing. It allows a much wider range of algorithms to be applied to the input data and can avoid problems such as the build-up of noise and distortion during processing. Since images are defined over two dimensions (perhaps more) digital image processing may be modeled in the form of multidimensional systems. ", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Machine learning", "Machine learning (ML) is a field of inquiry devoted to understanding and building methods that 'learn', that is, methods that leverage data to improve performance on some set of tasks. It is seen as a part of artificial intelligence. Machine learning algorithms build a model based on sample data, known as training data, in order to make predictions or decisions without being explicitly programmed to do so. Machine learning algorithms are used in a wide variety of applications, such as in medicine, email filtering, speech recognition, and computer vision, where it is difficult or unfeasible to develop conventional algorithms to perform the needed tasks.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Data Science", "Data science is an interdisciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of application domains. Data science is related to data mining, machine learning and big data. Data science is a concept to unify statistics, data analysis, informatics, and their related methods in order to understand and analyse actual phenomena with data.[3] It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Project Management", "Project management is the process of leading the work of a team to achieve all project goals within the given constraints. This information is usually described in project documentation, created at the beginning of the development process. The primary constraints are scope, time, and budget. The secondary challenge is to optimize the allocation of necessary inputs and apply them to meet pre-defined objectives.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Cloud Computing", "Cloud computing is the on-demand availability of computer system resources, especially data storage (cloud storage) and computing power, without direct active management by the user. Large clouds often have functions distributed over multiple locations, each location being a data center. Cloud computing relies on sharing of resources to achieve coherence and typically using a pay-as-you-go model which can help in reducing capital expenses but may also lead to unexpected operating expenses for unaware users.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Digital signal processing", "Digital signal processing (DSP) is the use of digital processing, such as by computers or more specialized digital signal processors, to perform a wide variety of signal processing operations. The digital signals processed in this manner are a sequence of numbers that represent samples of a continuous variable in a domain such as time, space, or frequency. In digital electronics, a digital signal is represented as a pulse train, which is typically generated by the switching of a transistor.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Embedded Systems", "An embedded system is a computer system—a combination of a computer processor, computer memory, and input/output peripheral devices—that has a dedicated function within a larger mechanical or electronic system. It is embedded as part of a complete device often including electrical or electronic hardware and mechanical parts. Because an embedded system typically controls physical operations of the machine that it is embedded within, it often has real-time computing constraints. Embedded systems control many devices in common use today.", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Natural language processing", "Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data. The goal is a computer capable of understanding the contents of documents, including the contextual nuances of the language within them. The technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));

INSERT INTO course(id, course_name, course_description, max_size, credit_unit, start_date, end_date) VALUES(uuid(), "Programming Concepts Using Python", "Python is a high-level, interpreted, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming. It is often described as a batteries included language due to its comprehensive standard library", 10, 5, (CAST('2022-02-25 00:00:00.000000' AS DateTime)), (CAST('2022-12-25 00:00:00.000000' AS DateTime)));
