package sg.edu.iss.caps.model;

public enum AppPage {
	ADMIN_MANAGE_STUDENTS,
	ADMIN_MANAGE_LECTURERS,
	ADMIN_MANAGE_COURSES,
	ADMIN_HOME,
	LECTURER_VIEW_COURSES,
	LECTURER_STUDENT_PERF,
	STUDENT_MY_COURSES,
	STUDENT_ENROLL
}
